# Default values for nginx-site-demo
# This is a YAML-formatted file.

serviceType: ClusterIP
servicePort: 80
containerPort: 80
component: "nginx-site-demo"
replicas: 3
image: "geoffh1977/nginx-site-demo"
imageTag: "latest"
imagePullPolicy: "Always"
cpu: "10m"
memory: "128Mi"
# Ingress settings
ingress:
  enabled: true
  hostname: demo.kube.local
  annotations:
     kubernetes.io/ingress.class: nginx
     # kubernetes.io/tls-acme: "true"
  tls: false
# PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
